# Generated by Django 4.2.7 on 2024-01-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_rename_borrow_list_bookissueretrunhistory_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissueretrunhistory',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
