# Generated by Django 4.2.8 on 2024-01-10 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('EEE', 'EEE'), ('ECE', 'ECE'), ('CE', 'CE'), ('ME', 'ME'), ('ACC', 'ACC'), ('NAME', 'NAME'), ('FIN', 'FIN'), ('ENG', 'ENG'), ('AIS', 'AIS'), ('ELT', 'ELT')], max_length=10)),
                ('faculty', models.CharField(choices=[('ENGINEERING', 'ENGINEERING'), ('ARTS', 'ARTS'), ('BUSSINESS', 'BUSSINESS')], max_length=19)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField(unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', related_query_name='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
